// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImPrivilegeUser(db *gorm.DB, opts ...gen.DOOption) imPrivilegeUser {
	_imPrivilegeUser := imPrivilegeUser{}

	_imPrivilegeUser.imPrivilegeUserDo.UseDB(db, opts...)
	_imPrivilegeUser.imPrivilegeUserDo.UseModel(&model.ImPrivilegeUser{})

	tableName := _imPrivilegeUser.imPrivilegeUserDo.TableName()
	_imPrivilegeUser.ALL = field.NewAsterisk(tableName)
	_imPrivilegeUser.ID = field.NewInt64(tableName, "id")
	_imPrivilegeUser.UserID = field.NewString(tableName, "user_id")
	_imPrivilegeUser.Account = field.NewString(tableName, "account")
	_imPrivilegeUser.Nickname = field.NewString(tableName, "nickname")
	_imPrivilegeUser.FriendPrivileges = field.NewInt32(tableName, "friend_privileges")
	_imPrivilegeUser.GroupPrivileges = field.NewInt32(tableName, "group_privileges")
	_imPrivilegeUser.CreatedAt = field.NewTime(tableName, "created_at")
	_imPrivilegeUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imPrivilegeUser.DeletedAt = field.NewField(tableName, "deleted_at")
	_imPrivilegeUser.CheckType = field.NewInt32(tableName, "check_type")

	_imPrivilegeUser.fillFieldMap()

	return _imPrivilegeUser
}

type imPrivilegeUser struct {
	imPrivilegeUserDo imPrivilegeUserDo

	ALL              field.Asterisk
	ID               field.Int64  // 主键id
	UserID           field.String // 用户ID 对应着腾讯的id
	Account          field.String // 帐户
	Nickname         field.String // 昵称
	FriendPrivileges field.Int32  // 好有特权 1站点禁止加好友时不受限制 2禁用
	GroupPrivileges  field.Int32  // 群组特权 1不受限制创建群聊 2禁用
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间
	DeletedAt        field.Field  // 删除时间
	CheckType        field.Int32  // 登录校验方式 0=不校验，1=IP校验，2=设备号校验

	fieldMap map[string]field.Expr
}

func (i imPrivilegeUser) Table(newTableName string) *imPrivilegeUser {
	i.imPrivilegeUserDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imPrivilegeUser) As(alias string) *imPrivilegeUser {
	i.imPrivilegeUserDo.DO = *(i.imPrivilegeUserDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imPrivilegeUser) updateTableName(table string) *imPrivilegeUser {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.UserID = field.NewString(table, "user_id")
	i.Account = field.NewString(table, "account")
	i.Nickname = field.NewString(table, "nickname")
	i.FriendPrivileges = field.NewInt32(table, "friend_privileges")
	i.GroupPrivileges = field.NewInt32(table, "group_privileges")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")
	i.CheckType = field.NewInt32(table, "check_type")

	i.fillFieldMap()

	return i
}

func (i *imPrivilegeUser) WithContext(ctx context.Context) *imPrivilegeUserDo {
	return i.imPrivilegeUserDo.WithContext(ctx)
}

func (i imPrivilegeUser) TableName() string { return i.imPrivilegeUserDo.TableName() }

func (i imPrivilegeUser) Alias() string { return i.imPrivilegeUserDo.Alias() }

func (i *imPrivilegeUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imPrivilegeUser) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["account"] = i.Account
	i.fieldMap["nickname"] = i.Nickname
	i.fieldMap["friend_privileges"] = i.FriendPrivileges
	i.fieldMap["group_privileges"] = i.GroupPrivileges
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
	i.fieldMap["check_type"] = i.CheckType
}

func (i imPrivilegeUser) clone(db *gorm.DB) imPrivilegeUser {
	i.imPrivilegeUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imPrivilegeUser) replaceDB(db *gorm.DB) imPrivilegeUser {
	i.imPrivilegeUserDo.ReplaceDB(db)
	return i
}

type imPrivilegeUserDo struct{ gen.DO }

func (i imPrivilegeUserDo) Debug() *imPrivilegeUserDo {
	return i.withDO(i.DO.Debug())
}

func (i imPrivilegeUserDo) WithContext(ctx context.Context) *imPrivilegeUserDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imPrivilegeUserDo) ReadDB() *imPrivilegeUserDo {
	return i.Clauses(dbresolver.Read)
}

func (i imPrivilegeUserDo) WriteDB() *imPrivilegeUserDo {
	return i.Clauses(dbresolver.Write)
}

func (i imPrivilegeUserDo) Session(config *gorm.Session) *imPrivilegeUserDo {
	return i.withDO(i.DO.Session(config))
}

func (i imPrivilegeUserDo) Clauses(conds ...clause.Expression) *imPrivilegeUserDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imPrivilegeUserDo) Returning(value interface{}, columns ...string) *imPrivilegeUserDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imPrivilegeUserDo) Not(conds ...gen.Condition) *imPrivilegeUserDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imPrivilegeUserDo) Or(conds ...gen.Condition) *imPrivilegeUserDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imPrivilegeUserDo) Select(conds ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imPrivilegeUserDo) Where(conds ...gen.Condition) *imPrivilegeUserDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imPrivilegeUserDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imPrivilegeUserDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imPrivilegeUserDo) Order(conds ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imPrivilegeUserDo) Distinct(cols ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imPrivilegeUserDo) Omit(cols ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imPrivilegeUserDo) Join(table schema.Tabler, on ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imPrivilegeUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imPrivilegeUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imPrivilegeUserDo) Group(cols ...field.Expr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imPrivilegeUserDo) Having(conds ...gen.Condition) *imPrivilegeUserDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imPrivilegeUserDo) Limit(limit int) *imPrivilegeUserDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imPrivilegeUserDo) Offset(offset int) *imPrivilegeUserDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imPrivilegeUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imPrivilegeUserDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imPrivilegeUserDo) Unscoped() *imPrivilegeUserDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imPrivilegeUserDo) Create(values ...*model.ImPrivilegeUser) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imPrivilegeUserDo) CreateInBatches(values []*model.ImPrivilegeUser, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imPrivilegeUserDo) Save(values ...*model.ImPrivilegeUser) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imPrivilegeUserDo) First() (*model.ImPrivilegeUser, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUser), nil
	}
}

func (i imPrivilegeUserDo) Take() (*model.ImPrivilegeUser, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUser), nil
	}
}

func (i imPrivilegeUserDo) Last() (*model.ImPrivilegeUser, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUser), nil
	}
}

func (i imPrivilegeUserDo) Find() ([]*model.ImPrivilegeUser, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImPrivilegeUser), err
}

func (i imPrivilegeUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImPrivilegeUser, err error) {
	buf := make([]*model.ImPrivilegeUser, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imPrivilegeUserDo) FindInBatches(result *[]*model.ImPrivilegeUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imPrivilegeUserDo) Attrs(attrs ...field.AssignExpr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imPrivilegeUserDo) Assign(attrs ...field.AssignExpr) *imPrivilegeUserDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imPrivilegeUserDo) Joins(fields ...field.RelationField) *imPrivilegeUserDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imPrivilegeUserDo) Preload(fields ...field.RelationField) *imPrivilegeUserDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imPrivilegeUserDo) FirstOrInit() (*model.ImPrivilegeUser, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUser), nil
	}
}

func (i imPrivilegeUserDo) FirstOrCreate() (*model.ImPrivilegeUser, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUser), nil
	}
}

func (i imPrivilegeUserDo) FindByPage(offset int, limit int) (result []*model.ImPrivilegeUser, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imPrivilegeUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imPrivilegeUserDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imPrivilegeUserDo) Delete(models ...*model.ImPrivilegeUser) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imPrivilegeUserDo) withDO(do gen.Dao) *imPrivilegeUserDo {
	i.DO = *do.(*gen.DO)
	return i
}
