// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImPrivilegeUserBindLoginIP(db *gorm.DB, opts ...gen.DOOption) imPrivilegeUserBindLoginIP {
	_imPrivilegeUserBindLoginIP := imPrivilegeUserBindLoginIP{}

	_imPrivilegeUserBindLoginIP.imPrivilegeUserBindLoginIPDo.UseDB(db, opts...)
	_imPrivilegeUserBindLoginIP.imPrivilegeUserBindLoginIPDo.UseModel(&model.ImPrivilegeUserBindLoginIP{})

	tableName := _imPrivilegeUserBindLoginIP.imPrivilegeUserBindLoginIPDo.TableName()
	_imPrivilegeUserBindLoginIP.ALL = field.NewAsterisk(tableName)
	_imPrivilegeUserBindLoginIP.ID = field.NewInt64(tableName, "id")
	_imPrivilegeUserBindLoginIP.UserID = field.NewString(tableName, "user_id")
	_imPrivilegeUserBindLoginIP.IP = field.NewString(tableName, "ip")
	_imPrivilegeUserBindLoginIP.CreatedAt = field.NewTime(tableName, "created_at")
	_imPrivilegeUserBindLoginIP.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imPrivilegeUserBindLoginIP.DeletedAt = field.NewField(tableName, "deleted_at")

	_imPrivilegeUserBindLoginIP.fillFieldMap()

	return _imPrivilegeUserBindLoginIP
}

type imPrivilegeUserBindLoginIP struct {
	imPrivilegeUserBindLoginIPDo imPrivilegeUserBindLoginIPDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键id
	UserID    field.String // 用户id
	IP        field.String // 绑定的登录IP
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (i imPrivilegeUserBindLoginIP) Table(newTableName string) *imPrivilegeUserBindLoginIP {
	i.imPrivilegeUserBindLoginIPDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imPrivilegeUserBindLoginIP) As(alias string) *imPrivilegeUserBindLoginIP {
	i.imPrivilegeUserBindLoginIPDo.DO = *(i.imPrivilegeUserBindLoginIPDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imPrivilegeUserBindLoginIP) updateTableName(table string) *imPrivilegeUserBindLoginIP {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.UserID = field.NewString(table, "user_id")
	i.IP = field.NewString(table, "ip")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")

	i.fillFieldMap()

	return i
}

func (i *imPrivilegeUserBindLoginIP) WithContext(ctx context.Context) *imPrivilegeUserBindLoginIPDo {
	return i.imPrivilegeUserBindLoginIPDo.WithContext(ctx)
}

func (i imPrivilegeUserBindLoginIP) TableName() string {
	return i.imPrivilegeUserBindLoginIPDo.TableName()
}

func (i imPrivilegeUserBindLoginIP) Alias() string { return i.imPrivilegeUserBindLoginIPDo.Alias() }

func (i *imPrivilegeUserBindLoginIP) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imPrivilegeUserBindLoginIP) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 6)
	i.fieldMap["id"] = i.ID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["ip"] = i.IP
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
}

func (i imPrivilegeUserBindLoginIP) clone(db *gorm.DB) imPrivilegeUserBindLoginIP {
	i.imPrivilegeUserBindLoginIPDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imPrivilegeUserBindLoginIP) replaceDB(db *gorm.DB) imPrivilegeUserBindLoginIP {
	i.imPrivilegeUserBindLoginIPDo.ReplaceDB(db)
	return i
}

type imPrivilegeUserBindLoginIPDo struct{ gen.DO }

func (i imPrivilegeUserBindLoginIPDo) Debug() *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Debug())
}

func (i imPrivilegeUserBindLoginIPDo) WithContext(ctx context.Context) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imPrivilegeUserBindLoginIPDo) ReadDB() *imPrivilegeUserBindLoginIPDo {
	return i.Clauses(dbresolver.Read)
}

func (i imPrivilegeUserBindLoginIPDo) WriteDB() *imPrivilegeUserBindLoginIPDo {
	return i.Clauses(dbresolver.Write)
}

func (i imPrivilegeUserBindLoginIPDo) Session(config *gorm.Session) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Session(config))
}

func (i imPrivilegeUserBindLoginIPDo) Clauses(conds ...clause.Expression) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Returning(value interface{}, columns ...string) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imPrivilegeUserBindLoginIPDo) Not(conds ...gen.Condition) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Or(conds ...gen.Condition) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Select(conds ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Where(conds ...gen.Condition) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imPrivilegeUserBindLoginIPDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imPrivilegeUserBindLoginIPDo) Order(conds ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Distinct(cols ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imPrivilegeUserBindLoginIPDo) Omit(cols ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imPrivilegeUserBindLoginIPDo) Join(table schema.Tabler, on ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imPrivilegeUserBindLoginIPDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imPrivilegeUserBindLoginIPDo) RightJoin(table schema.Tabler, on ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imPrivilegeUserBindLoginIPDo) Group(cols ...field.Expr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imPrivilegeUserBindLoginIPDo) Having(conds ...gen.Condition) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imPrivilegeUserBindLoginIPDo) Limit(limit int) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imPrivilegeUserBindLoginIPDo) Offset(offset int) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imPrivilegeUserBindLoginIPDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imPrivilegeUserBindLoginIPDo) Unscoped() *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imPrivilegeUserBindLoginIPDo) Create(values ...*model.ImPrivilegeUserBindLoginIP) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imPrivilegeUserBindLoginIPDo) CreateInBatches(values []*model.ImPrivilegeUserBindLoginIP, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imPrivilegeUserBindLoginIPDo) Save(values ...*model.ImPrivilegeUserBindLoginIP) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imPrivilegeUserBindLoginIPDo) First() (*model.ImPrivilegeUserBindLoginIP, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginIP), nil
	}
}

func (i imPrivilegeUserBindLoginIPDo) Take() (*model.ImPrivilegeUserBindLoginIP, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginIP), nil
	}
}

func (i imPrivilegeUserBindLoginIPDo) Last() (*model.ImPrivilegeUserBindLoginIP, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginIP), nil
	}
}

func (i imPrivilegeUserBindLoginIPDo) Find() ([]*model.ImPrivilegeUserBindLoginIP, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImPrivilegeUserBindLoginIP), err
}

func (i imPrivilegeUserBindLoginIPDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImPrivilegeUserBindLoginIP, err error) {
	buf := make([]*model.ImPrivilegeUserBindLoginIP, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imPrivilegeUserBindLoginIPDo) FindInBatches(result *[]*model.ImPrivilegeUserBindLoginIP, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imPrivilegeUserBindLoginIPDo) Attrs(attrs ...field.AssignExpr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imPrivilegeUserBindLoginIPDo) Assign(attrs ...field.AssignExpr) *imPrivilegeUserBindLoginIPDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imPrivilegeUserBindLoginIPDo) Joins(fields ...field.RelationField) *imPrivilegeUserBindLoginIPDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imPrivilegeUserBindLoginIPDo) Preload(fields ...field.RelationField) *imPrivilegeUserBindLoginIPDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imPrivilegeUserBindLoginIPDo) FirstOrInit() (*model.ImPrivilegeUserBindLoginIP, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginIP), nil
	}
}

func (i imPrivilegeUserBindLoginIPDo) FirstOrCreate() (*model.ImPrivilegeUserBindLoginIP, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginIP), nil
	}
}

func (i imPrivilegeUserBindLoginIPDo) FindByPage(offset int, limit int) (result []*model.ImPrivilegeUserBindLoginIP, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imPrivilegeUserBindLoginIPDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imPrivilegeUserBindLoginIPDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imPrivilegeUserBindLoginIPDo) Delete(models ...*model.ImPrivilegeUserBindLoginIP) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imPrivilegeUserBindLoginIPDo) withDO(do gen.Dao) *imPrivilegeUserBindLoginIPDo {
	i.DO = *do.(*gen.DO)
	return i
}
