// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImPrivilegeUserBindLoginDevice(db *gorm.DB, opts ...gen.DOOption) imPrivilegeUserBindLoginDevice {
	_imPrivilegeUserBindLoginDevice := imPrivilegeUserBindLoginDevice{}

	_imPrivilegeUserBindLoginDevice.imPrivilegeUserBindLoginDeviceDo.UseDB(db, opts...)
	_imPrivilegeUserBindLoginDevice.imPrivilegeUserBindLoginDeviceDo.UseModel(&model.ImPrivilegeUserBindLoginDevice{})

	tableName := _imPrivilegeUserBindLoginDevice.imPrivilegeUserBindLoginDeviceDo.TableName()
	_imPrivilegeUserBindLoginDevice.ALL = field.NewAsterisk(tableName)
	_imPrivilegeUserBindLoginDevice.ID = field.NewInt64(tableName, "id")
	_imPrivilegeUserBindLoginDevice.UserID = field.NewString(tableName, "user_id")
	_imPrivilegeUserBindLoginDevice.Device = field.NewString(tableName, "device")
	_imPrivilegeUserBindLoginDevice.CreatedAt = field.NewTime(tableName, "created_at")
	_imPrivilegeUserBindLoginDevice.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imPrivilegeUserBindLoginDevice.DeletedAt = field.NewField(tableName, "deleted_at")

	_imPrivilegeUserBindLoginDevice.fillFieldMap()

	return _imPrivilegeUserBindLoginDevice
}

type imPrivilegeUserBindLoginDevice struct {
	imPrivilegeUserBindLoginDeviceDo imPrivilegeUserBindLoginDeviceDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键id
	UserID    field.String // 用户id
	Device    field.String // 绑定的登录设备号
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (i imPrivilegeUserBindLoginDevice) Table(newTableName string) *imPrivilegeUserBindLoginDevice {
	i.imPrivilegeUserBindLoginDeviceDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imPrivilegeUserBindLoginDevice) As(alias string) *imPrivilegeUserBindLoginDevice {
	i.imPrivilegeUserBindLoginDeviceDo.DO = *(i.imPrivilegeUserBindLoginDeviceDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imPrivilegeUserBindLoginDevice) updateTableName(table string) *imPrivilegeUserBindLoginDevice {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.UserID = field.NewString(table, "user_id")
	i.Device = field.NewString(table, "device")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")

	i.fillFieldMap()

	return i
}

func (i *imPrivilegeUserBindLoginDevice) WithContext(ctx context.Context) *imPrivilegeUserBindLoginDeviceDo {
	return i.imPrivilegeUserBindLoginDeviceDo.WithContext(ctx)
}

func (i imPrivilegeUserBindLoginDevice) TableName() string {
	return i.imPrivilegeUserBindLoginDeviceDo.TableName()
}

func (i imPrivilegeUserBindLoginDevice) Alias() string {
	return i.imPrivilegeUserBindLoginDeviceDo.Alias()
}

func (i *imPrivilegeUserBindLoginDevice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imPrivilegeUserBindLoginDevice) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 6)
	i.fieldMap["id"] = i.ID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["device"] = i.Device
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
}

func (i imPrivilegeUserBindLoginDevice) clone(db *gorm.DB) imPrivilegeUserBindLoginDevice {
	i.imPrivilegeUserBindLoginDeviceDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imPrivilegeUserBindLoginDevice) replaceDB(db *gorm.DB) imPrivilegeUserBindLoginDevice {
	i.imPrivilegeUserBindLoginDeviceDo.ReplaceDB(db)
	return i
}

type imPrivilegeUserBindLoginDeviceDo struct{ gen.DO }

func (i imPrivilegeUserBindLoginDeviceDo) Debug() *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Debug())
}

func (i imPrivilegeUserBindLoginDeviceDo) WithContext(ctx context.Context) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imPrivilegeUserBindLoginDeviceDo) ReadDB() *imPrivilegeUserBindLoginDeviceDo {
	return i.Clauses(dbresolver.Read)
}

func (i imPrivilegeUserBindLoginDeviceDo) WriteDB() *imPrivilegeUserBindLoginDeviceDo {
	return i.Clauses(dbresolver.Write)
}

func (i imPrivilegeUserBindLoginDeviceDo) Session(config *gorm.Session) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Session(config))
}

func (i imPrivilegeUserBindLoginDeviceDo) Clauses(conds ...clause.Expression) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Returning(value interface{}, columns ...string) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Not(conds ...gen.Condition) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Or(conds ...gen.Condition) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Select(conds ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Where(conds ...gen.Condition) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imPrivilegeUserBindLoginDeviceDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imPrivilegeUserBindLoginDeviceDo) Order(conds ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Distinct(cols ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Omit(cols ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Join(table schema.Tabler, on ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imPrivilegeUserBindLoginDeviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imPrivilegeUserBindLoginDeviceDo) RightJoin(table schema.Tabler, on ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Group(cols ...field.Expr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Having(conds ...gen.Condition) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Limit(limit int) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imPrivilegeUserBindLoginDeviceDo) Offset(offset int) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imPrivilegeUserBindLoginDeviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Unscoped() *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imPrivilegeUserBindLoginDeviceDo) Create(values ...*model.ImPrivilegeUserBindLoginDevice) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imPrivilegeUserBindLoginDeviceDo) CreateInBatches(values []*model.ImPrivilegeUserBindLoginDevice, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imPrivilegeUserBindLoginDeviceDo) Save(values ...*model.ImPrivilegeUserBindLoginDevice) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imPrivilegeUserBindLoginDeviceDo) First() (*model.ImPrivilegeUserBindLoginDevice, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginDevice), nil
	}
}

func (i imPrivilegeUserBindLoginDeviceDo) Take() (*model.ImPrivilegeUserBindLoginDevice, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginDevice), nil
	}
}

func (i imPrivilegeUserBindLoginDeviceDo) Last() (*model.ImPrivilegeUserBindLoginDevice, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginDevice), nil
	}
}

func (i imPrivilegeUserBindLoginDeviceDo) Find() ([]*model.ImPrivilegeUserBindLoginDevice, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImPrivilegeUserBindLoginDevice), err
}

func (i imPrivilegeUserBindLoginDeviceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImPrivilegeUserBindLoginDevice, err error) {
	buf := make([]*model.ImPrivilegeUserBindLoginDevice, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imPrivilegeUserBindLoginDeviceDo) FindInBatches(result *[]*model.ImPrivilegeUserBindLoginDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imPrivilegeUserBindLoginDeviceDo) Attrs(attrs ...field.AssignExpr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Assign(attrs ...field.AssignExpr) *imPrivilegeUserBindLoginDeviceDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imPrivilegeUserBindLoginDeviceDo) Joins(fields ...field.RelationField) *imPrivilegeUserBindLoginDeviceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imPrivilegeUserBindLoginDeviceDo) Preload(fields ...field.RelationField) *imPrivilegeUserBindLoginDeviceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imPrivilegeUserBindLoginDeviceDo) FirstOrInit() (*model.ImPrivilegeUserBindLoginDevice, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginDevice), nil
	}
}

func (i imPrivilegeUserBindLoginDeviceDo) FirstOrCreate() (*model.ImPrivilegeUserBindLoginDevice, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImPrivilegeUserBindLoginDevice), nil
	}
}

func (i imPrivilegeUserBindLoginDeviceDo) FindByPage(offset int, limit int) (result []*model.ImPrivilegeUserBindLoginDevice, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imPrivilegeUserBindLoginDeviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imPrivilegeUserBindLoginDeviceDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imPrivilegeUserBindLoginDeviceDo) Delete(models ...*model.ImPrivilegeUserBindLoginDevice) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imPrivilegeUserBindLoginDeviceDo) withDO(do gen.Dao) *imPrivilegeUserBindLoginDeviceDo {
	i.DO = *do.(*gen.DO)
	return i
}
