// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImRobot(db *gorm.DB, opts ...gen.DOOption) imRobot {
	_imRobot := imRobot{}

	_imRobot.imRobotDo.UseDB(db, opts...)
	_imRobot.imRobotDo.UseModel(&model.ImRobot{})

	tableName := _imRobot.imRobotDo.TableName()
	_imRobot.ALL = field.NewAsterisk(tableName)
	_imRobot.ID = field.NewInt64(tableName, "id")
	_imRobot.UserID = field.NewString(tableName, "user_id")
	_imRobot.Nickname = field.NewString(tableName, "nickname")
	_imRobot.FaceURL = field.NewString(tableName, "face_url")
	_imRobot.Gender = field.NewInt32(tableName, "gender")
	_imRobot.Motto = field.NewString(tableName, "motto")
	_imRobot.Status = field.NewInt32(tableName, "status")
	_imRobot.CreatedAt = field.NewTime(tableName, "created_at")
	_imRobot.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imRobot.DeletedAt = field.NewField(tableName, "deleted_at")

	_imRobot.fillFieldMap()

	return _imRobot
}

type imRobot struct {
	imRobotDo imRobotDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键id
	UserID    field.String // 用户ID 对应着腾讯的id
	Nickname  field.String // 昵称
	FaceURL   field.String // 头像
	Gender    field.Int32  // 性别 0=女性，1=男性
	Motto     field.String // 签名
	Status    field.Int32  // 状态 0=禁用，1=正常
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (i imRobot) Table(newTableName string) *imRobot {
	i.imRobotDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imRobot) As(alias string) *imRobot {
	i.imRobotDo.DO = *(i.imRobotDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imRobot) updateTableName(table string) *imRobot {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.UserID = field.NewString(table, "user_id")
	i.Nickname = field.NewString(table, "nickname")
	i.FaceURL = field.NewString(table, "face_url")
	i.Gender = field.NewInt32(table, "gender")
	i.Motto = field.NewString(table, "motto")
	i.Status = field.NewInt32(table, "status")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")

	i.fillFieldMap()

	return i
}

func (i *imRobot) WithContext(ctx context.Context) *imRobotDo { return i.imRobotDo.WithContext(ctx) }

func (i imRobot) TableName() string { return i.imRobotDo.TableName() }

func (i imRobot) Alias() string { return i.imRobotDo.Alias() }

func (i *imRobot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imRobot) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["id"] = i.ID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["nickname"] = i.Nickname
	i.fieldMap["face_url"] = i.FaceURL
	i.fieldMap["gender"] = i.Gender
	i.fieldMap["motto"] = i.Motto
	i.fieldMap["status"] = i.Status
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
}

func (i imRobot) clone(db *gorm.DB) imRobot {
	i.imRobotDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imRobot) replaceDB(db *gorm.DB) imRobot {
	i.imRobotDo.ReplaceDB(db)
	return i
}

type imRobotDo struct{ gen.DO }

func (i imRobotDo) Debug() *imRobotDo {
	return i.withDO(i.DO.Debug())
}

func (i imRobotDo) WithContext(ctx context.Context) *imRobotDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imRobotDo) ReadDB() *imRobotDo {
	return i.Clauses(dbresolver.Read)
}

func (i imRobotDo) WriteDB() *imRobotDo {
	return i.Clauses(dbresolver.Write)
}

func (i imRobotDo) Session(config *gorm.Session) *imRobotDo {
	return i.withDO(i.DO.Session(config))
}

func (i imRobotDo) Clauses(conds ...clause.Expression) *imRobotDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imRobotDo) Returning(value interface{}, columns ...string) *imRobotDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imRobotDo) Not(conds ...gen.Condition) *imRobotDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imRobotDo) Or(conds ...gen.Condition) *imRobotDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imRobotDo) Select(conds ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imRobotDo) Where(conds ...gen.Condition) *imRobotDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imRobotDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imRobotDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imRobotDo) Order(conds ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imRobotDo) Distinct(cols ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imRobotDo) Omit(cols ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imRobotDo) Join(table schema.Tabler, on ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imRobotDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imRobotDo) RightJoin(table schema.Tabler, on ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imRobotDo) Group(cols ...field.Expr) *imRobotDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imRobotDo) Having(conds ...gen.Condition) *imRobotDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imRobotDo) Limit(limit int) *imRobotDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imRobotDo) Offset(offset int) *imRobotDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imRobotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imRobotDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imRobotDo) Unscoped() *imRobotDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imRobotDo) Create(values ...*model.ImRobot) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imRobotDo) CreateInBatches(values []*model.ImRobot, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imRobotDo) Save(values ...*model.ImRobot) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imRobotDo) First() (*model.ImRobot, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImRobot), nil
	}
}

func (i imRobotDo) Take() (*model.ImRobot, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImRobot), nil
	}
}

func (i imRobotDo) Last() (*model.ImRobot, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImRobot), nil
	}
}

func (i imRobotDo) Find() ([]*model.ImRobot, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImRobot), err
}

func (i imRobotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImRobot, err error) {
	buf := make([]*model.ImRobot, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imRobotDo) FindInBatches(result *[]*model.ImRobot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imRobotDo) Attrs(attrs ...field.AssignExpr) *imRobotDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imRobotDo) Assign(attrs ...field.AssignExpr) *imRobotDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imRobotDo) Joins(fields ...field.RelationField) *imRobotDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imRobotDo) Preload(fields ...field.RelationField) *imRobotDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imRobotDo) FirstOrInit() (*model.ImRobot, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImRobot), nil
	}
}

func (i imRobotDo) FirstOrCreate() (*model.ImRobot, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImRobot), nil
	}
}

func (i imRobotDo) FindByPage(offset int, limit int) (result []*model.ImRobot, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imRobotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imRobotDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imRobotDo) Delete(models ...*model.ImRobot) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imRobotDo) withDO(do gen.Dao) *imRobotDo {
	i.DO = *do.(*gen.DO)
	return i
}
