// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImSecurityQuestion(db *gorm.DB, opts ...gen.DOOption) imSecurityQuestion {
	_imSecurityQuestion := imSecurityQuestion{}

	_imSecurityQuestion.imSecurityQuestionDo.UseDB(db, opts...)
	_imSecurityQuestion.imSecurityQuestionDo.UseModel(&model.ImSecurityQuestion{})

	tableName := _imSecurityQuestion.imSecurityQuestionDo.TableName()
	_imSecurityQuestion.ALL = field.NewAsterisk(tableName)
	_imSecurityQuestion.ID = field.NewInt32(tableName, "id")
	_imSecurityQuestion.Question = field.NewString(tableName, "question")
	_imSecurityQuestion.QuestionEn = field.NewString(tableName, "question_en")

	_imSecurityQuestion.fillFieldMap()

	return _imSecurityQuestion
}

type imSecurityQuestion struct {
	imSecurityQuestionDo imSecurityQuestionDo

	ALL        field.Asterisk
	ID         field.Int32 // 自增ID
	Question   field.String
	QuestionEn field.String

	fieldMap map[string]field.Expr
}

func (i imSecurityQuestion) Table(newTableName string) *imSecurityQuestion {
	i.imSecurityQuestionDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imSecurityQuestion) As(alias string) *imSecurityQuestion {
	i.imSecurityQuestionDo.DO = *(i.imSecurityQuestionDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imSecurityQuestion) updateTableName(table string) *imSecurityQuestion {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt32(table, "id")
	i.Question = field.NewString(table, "question")
	i.QuestionEn = field.NewString(table, "question_en")

	i.fillFieldMap()

	return i
}

func (i *imSecurityQuestion) WithContext(ctx context.Context) *imSecurityQuestionDo {
	return i.imSecurityQuestionDo.WithContext(ctx)
}

func (i imSecurityQuestion) TableName() string { return i.imSecurityQuestionDo.TableName() }

func (i imSecurityQuestion) Alias() string { return i.imSecurityQuestionDo.Alias() }

func (i *imSecurityQuestion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imSecurityQuestion) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 3)
	i.fieldMap["id"] = i.ID
	i.fieldMap["question"] = i.Question
	i.fieldMap["question_en"] = i.QuestionEn
}

func (i imSecurityQuestion) clone(db *gorm.DB) imSecurityQuestion {
	i.imSecurityQuestionDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imSecurityQuestion) replaceDB(db *gorm.DB) imSecurityQuestion {
	i.imSecurityQuestionDo.ReplaceDB(db)
	return i
}

type imSecurityQuestionDo struct{ gen.DO }

func (i imSecurityQuestionDo) Debug() *imSecurityQuestionDo {
	return i.withDO(i.DO.Debug())
}

func (i imSecurityQuestionDo) WithContext(ctx context.Context) *imSecurityQuestionDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imSecurityQuestionDo) ReadDB() *imSecurityQuestionDo {
	return i.Clauses(dbresolver.Read)
}

func (i imSecurityQuestionDo) WriteDB() *imSecurityQuestionDo {
	return i.Clauses(dbresolver.Write)
}

func (i imSecurityQuestionDo) Session(config *gorm.Session) *imSecurityQuestionDo {
	return i.withDO(i.DO.Session(config))
}

func (i imSecurityQuestionDo) Clauses(conds ...clause.Expression) *imSecurityQuestionDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imSecurityQuestionDo) Returning(value interface{}, columns ...string) *imSecurityQuestionDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imSecurityQuestionDo) Not(conds ...gen.Condition) *imSecurityQuestionDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imSecurityQuestionDo) Or(conds ...gen.Condition) *imSecurityQuestionDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imSecurityQuestionDo) Select(conds ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imSecurityQuestionDo) Where(conds ...gen.Condition) *imSecurityQuestionDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imSecurityQuestionDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imSecurityQuestionDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imSecurityQuestionDo) Order(conds ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imSecurityQuestionDo) Distinct(cols ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imSecurityQuestionDo) Omit(cols ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imSecurityQuestionDo) Join(table schema.Tabler, on ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imSecurityQuestionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imSecurityQuestionDo) RightJoin(table schema.Tabler, on ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imSecurityQuestionDo) Group(cols ...field.Expr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imSecurityQuestionDo) Having(conds ...gen.Condition) *imSecurityQuestionDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imSecurityQuestionDo) Limit(limit int) *imSecurityQuestionDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imSecurityQuestionDo) Offset(offset int) *imSecurityQuestionDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imSecurityQuestionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imSecurityQuestionDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imSecurityQuestionDo) Unscoped() *imSecurityQuestionDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imSecurityQuestionDo) Create(values ...*model.ImSecurityQuestion) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imSecurityQuestionDo) CreateInBatches(values []*model.ImSecurityQuestion, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imSecurityQuestionDo) Save(values ...*model.ImSecurityQuestion) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imSecurityQuestionDo) First() (*model.ImSecurityQuestion, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImSecurityQuestion), nil
	}
}

func (i imSecurityQuestionDo) Take() (*model.ImSecurityQuestion, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImSecurityQuestion), nil
	}
}

func (i imSecurityQuestionDo) Last() (*model.ImSecurityQuestion, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImSecurityQuestion), nil
	}
}

func (i imSecurityQuestionDo) Find() ([]*model.ImSecurityQuestion, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImSecurityQuestion), err
}

func (i imSecurityQuestionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImSecurityQuestion, err error) {
	buf := make([]*model.ImSecurityQuestion, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imSecurityQuestionDo) FindInBatches(result *[]*model.ImSecurityQuestion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imSecurityQuestionDo) Attrs(attrs ...field.AssignExpr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imSecurityQuestionDo) Assign(attrs ...field.AssignExpr) *imSecurityQuestionDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imSecurityQuestionDo) Joins(fields ...field.RelationField) *imSecurityQuestionDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imSecurityQuestionDo) Preload(fields ...field.RelationField) *imSecurityQuestionDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imSecurityQuestionDo) FirstOrInit() (*model.ImSecurityQuestion, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImSecurityQuestion), nil
	}
}

func (i imSecurityQuestionDo) FirstOrCreate() (*model.ImSecurityQuestion, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImSecurityQuestion), nil
	}
}

func (i imSecurityQuestionDo) FindByPage(offset int, limit int) (result []*model.ImSecurityQuestion, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imSecurityQuestionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imSecurityQuestionDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imSecurityQuestionDo) Delete(models ...*model.ImSecurityQuestion) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imSecurityQuestionDo) withDO(do gen.Dao) *imSecurityQuestionDo {
	i.DO = *do.(*gen.DO)
	return i
}
