// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImUsersDeviceConf(db *gorm.DB, opts ...gen.DOOption) imUsersDeviceConf {
	_imUsersDeviceConf := imUsersDeviceConf{}

	_imUsersDeviceConf.imUsersDeviceConfDo.UseDB(db, opts...)
	_imUsersDeviceConf.imUsersDeviceConfDo.UseModel(&model.ImUsersDeviceConf{})

	tableName := _imUsersDeviceConf.imUsersDeviceConfDo.TableName()
	_imUsersDeviceConf.ALL = field.NewAsterisk(tableName)
	_imUsersDeviceConf.UserID = field.NewString(tableName, "user_id")
	_imUsersDeviceConf.MultiplePlatform = field.NewInt32(tableName, "multiplePlatform")
	_imUsersDeviceConf.Android = field.NewInt32(tableName, "android")
	_imUsersDeviceConf.Iphone = field.NewInt32(tableName, "iphone")
	_imUsersDeviceConf.Windows = field.NewInt32(tableName, "windows")
	_imUsersDeviceConf.Mac = field.NewInt32(tableName, "mac")
	_imUsersDeviceConf.CreatedAt = field.NewTime(tableName, "created_at")
	_imUsersDeviceConf.UpdatedAt = field.NewTime(tableName, "updated_at")

	_imUsersDeviceConf.fillFieldMap()

	return _imUsersDeviceConf
}

type imUsersDeviceConf struct {
	imUsersDeviceConfDo imUsersDeviceConfDo

	ALL              field.Asterisk
	UserID           field.String // 用户id
	MultiplePlatform field.Int32  // 多平台，1-单平台，2-多平台
	Android          field.Int32  // android平台,1-开通，2-没开通
	Iphone           field.Int32  // iphone平台,1-开通，2-没开通
	Windows          field.Int32  // windows平台,1-开通，2-没开通
	Mac              field.Int32  // mac平台,1-开通，2-没开通
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (i imUsersDeviceConf) Table(newTableName string) *imUsersDeviceConf {
	i.imUsersDeviceConfDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imUsersDeviceConf) As(alias string) *imUsersDeviceConf {
	i.imUsersDeviceConfDo.DO = *(i.imUsersDeviceConfDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imUsersDeviceConf) updateTableName(table string) *imUsersDeviceConf {
	i.ALL = field.NewAsterisk(table)
	i.UserID = field.NewString(table, "user_id")
	i.MultiplePlatform = field.NewInt32(table, "multiplePlatform")
	i.Android = field.NewInt32(table, "android")
	i.Iphone = field.NewInt32(table, "iphone")
	i.Windows = field.NewInt32(table, "windows")
	i.Mac = field.NewInt32(table, "mac")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *imUsersDeviceConf) WithContext(ctx context.Context) *imUsersDeviceConfDo {
	return i.imUsersDeviceConfDo.WithContext(ctx)
}

func (i imUsersDeviceConf) TableName() string { return i.imUsersDeviceConfDo.TableName() }

func (i imUsersDeviceConf) Alias() string { return i.imUsersDeviceConfDo.Alias() }

func (i *imUsersDeviceConf) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imUsersDeviceConf) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 8)
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["multiplePlatform"] = i.MultiplePlatform
	i.fieldMap["android"] = i.Android
	i.fieldMap["iphone"] = i.Iphone
	i.fieldMap["windows"] = i.Windows
	i.fieldMap["mac"] = i.Mac
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i imUsersDeviceConf) clone(db *gorm.DB) imUsersDeviceConf {
	i.imUsersDeviceConfDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imUsersDeviceConf) replaceDB(db *gorm.DB) imUsersDeviceConf {
	i.imUsersDeviceConfDo.ReplaceDB(db)
	return i
}

type imUsersDeviceConfDo struct{ gen.DO }

func (i imUsersDeviceConfDo) Debug() *imUsersDeviceConfDo {
	return i.withDO(i.DO.Debug())
}

func (i imUsersDeviceConfDo) WithContext(ctx context.Context) *imUsersDeviceConfDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imUsersDeviceConfDo) ReadDB() *imUsersDeviceConfDo {
	return i.Clauses(dbresolver.Read)
}

func (i imUsersDeviceConfDo) WriteDB() *imUsersDeviceConfDo {
	return i.Clauses(dbresolver.Write)
}

func (i imUsersDeviceConfDo) Session(config *gorm.Session) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Session(config))
}

func (i imUsersDeviceConfDo) Clauses(conds ...clause.Expression) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imUsersDeviceConfDo) Returning(value interface{}, columns ...string) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imUsersDeviceConfDo) Not(conds ...gen.Condition) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imUsersDeviceConfDo) Or(conds ...gen.Condition) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imUsersDeviceConfDo) Select(conds ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imUsersDeviceConfDo) Where(conds ...gen.Condition) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imUsersDeviceConfDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imUsersDeviceConfDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imUsersDeviceConfDo) Order(conds ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imUsersDeviceConfDo) Distinct(cols ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imUsersDeviceConfDo) Omit(cols ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imUsersDeviceConfDo) Join(table schema.Tabler, on ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imUsersDeviceConfDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imUsersDeviceConfDo) RightJoin(table schema.Tabler, on ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imUsersDeviceConfDo) Group(cols ...field.Expr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imUsersDeviceConfDo) Having(conds ...gen.Condition) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imUsersDeviceConfDo) Limit(limit int) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imUsersDeviceConfDo) Offset(offset int) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imUsersDeviceConfDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imUsersDeviceConfDo) Unscoped() *imUsersDeviceConfDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imUsersDeviceConfDo) Create(values ...*model.ImUsersDeviceConf) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imUsersDeviceConfDo) CreateInBatches(values []*model.ImUsersDeviceConf, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imUsersDeviceConfDo) Save(values ...*model.ImUsersDeviceConf) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imUsersDeviceConfDo) First() (*model.ImUsersDeviceConf, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUsersDeviceConf), nil
	}
}

func (i imUsersDeviceConfDo) Take() (*model.ImUsersDeviceConf, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUsersDeviceConf), nil
	}
}

func (i imUsersDeviceConfDo) Last() (*model.ImUsersDeviceConf, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUsersDeviceConf), nil
	}
}

func (i imUsersDeviceConfDo) Find() ([]*model.ImUsersDeviceConf, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImUsersDeviceConf), err
}

func (i imUsersDeviceConfDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImUsersDeviceConf, err error) {
	buf := make([]*model.ImUsersDeviceConf, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imUsersDeviceConfDo) FindInBatches(result *[]*model.ImUsersDeviceConf, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imUsersDeviceConfDo) Attrs(attrs ...field.AssignExpr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imUsersDeviceConfDo) Assign(attrs ...field.AssignExpr) *imUsersDeviceConfDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imUsersDeviceConfDo) Joins(fields ...field.RelationField) *imUsersDeviceConfDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imUsersDeviceConfDo) Preload(fields ...field.RelationField) *imUsersDeviceConfDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imUsersDeviceConfDo) FirstOrInit() (*model.ImUsersDeviceConf, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUsersDeviceConf), nil
	}
}

func (i imUsersDeviceConfDo) FirstOrCreate() (*model.ImUsersDeviceConf, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUsersDeviceConf), nil
	}
}

func (i imUsersDeviceConfDo) FindByPage(offset int, limit int) (result []*model.ImUsersDeviceConf, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imUsersDeviceConfDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imUsersDeviceConfDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imUsersDeviceConfDo) Delete(models ...*model.ImUsersDeviceConf) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imUsersDeviceConfDo) withDO(do gen.Dao) *imUsersDeviceConfDo {
	i.DO = *do.(*gen.DO)
	return i
}
