// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"fctl/dal/model"
)

func newImUserProhibitedBehavior(db *gorm.DB, opts ...gen.DOOption) imUserProhibitedBehavior {
	_imUserProhibitedBehavior := imUserProhibitedBehavior{}

	_imUserProhibitedBehavior.imUserProhibitedBehaviorDo.UseDB(db, opts...)
	_imUserProhibitedBehavior.imUserProhibitedBehaviorDo.UseModel(&model.ImUserProhibitedBehavior{})

	tableName := _imUserProhibitedBehavior.imUserProhibitedBehaviorDo.TableName()
	_imUserProhibitedBehavior.ALL = field.NewAsterisk(tableName)
	_imUserProhibitedBehavior.UserID = field.NewString(tableName, "user_id")
	_imUserProhibitedBehavior.Account = field.NewString(tableName, "account")
	_imUserProhibitedBehavior.Nickname = field.NewString(tableName, "nickname")
	_imUserProhibitedBehavior.ActionType = field.NewInt32(tableName, "action_type")
	_imUserProhibitedBehavior.EndTime = field.NewTime(tableName, "end_time")
	_imUserProhibitedBehavior.CreateBy = field.NewString(tableName, "create_by")
	_imUserProhibitedBehavior.UpdateBy = field.NewString(tableName, "update_by")
	_imUserProhibitedBehavior.CreatedAt = field.NewTime(tableName, "created_at")
	_imUserProhibitedBehavior.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imUserProhibitedBehavior.Remark = field.NewString(tableName, "remark")

	_imUserProhibitedBehavior.fillFieldMap()

	return _imUserProhibitedBehavior
}

type imUserProhibitedBehavior struct {
	imUserProhibitedBehaviorDo imUserProhibitedBehaviorDo

	ALL        field.Asterisk
	UserID     field.String // 用户ID
	Account    field.String // 帐户ID
	Nickname   field.String // 昵称
	ActionType field.Int32  // 行为类型 1=私聊禁言，2=群聊禁言，3=群聊禁言，3=禁止创建群聊，4=禁止登录
	EndTime    field.Time   // 禁止截止时间
	CreateBy   field.String // 创建人
	UpdateBy   field.String // 更新人
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	Remark     field.String // 封禁备注

	fieldMap map[string]field.Expr
}

func (i imUserProhibitedBehavior) Table(newTableName string) *imUserProhibitedBehavior {
	i.imUserProhibitedBehaviorDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imUserProhibitedBehavior) As(alias string) *imUserProhibitedBehavior {
	i.imUserProhibitedBehaviorDo.DO = *(i.imUserProhibitedBehaviorDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imUserProhibitedBehavior) updateTableName(table string) *imUserProhibitedBehavior {
	i.ALL = field.NewAsterisk(table)
	i.UserID = field.NewString(table, "user_id")
	i.Account = field.NewString(table, "account")
	i.Nickname = field.NewString(table, "nickname")
	i.ActionType = field.NewInt32(table, "action_type")
	i.EndTime = field.NewTime(table, "end_time")
	i.CreateBy = field.NewString(table, "create_by")
	i.UpdateBy = field.NewString(table, "update_by")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.Remark = field.NewString(table, "remark")

	i.fillFieldMap()

	return i
}

func (i *imUserProhibitedBehavior) WithContext(ctx context.Context) *imUserProhibitedBehaviorDo {
	return i.imUserProhibitedBehaviorDo.WithContext(ctx)
}

func (i imUserProhibitedBehavior) TableName() string { return i.imUserProhibitedBehaviorDo.TableName() }

func (i imUserProhibitedBehavior) Alias() string { return i.imUserProhibitedBehaviorDo.Alias() }

func (i *imUserProhibitedBehavior) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imUserProhibitedBehavior) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 10)
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["account"] = i.Account
	i.fieldMap["nickname"] = i.Nickname
	i.fieldMap["action_type"] = i.ActionType
	i.fieldMap["end_time"] = i.EndTime
	i.fieldMap["create_by"] = i.CreateBy
	i.fieldMap["update_by"] = i.UpdateBy
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["remark"] = i.Remark
}

func (i imUserProhibitedBehavior) clone(db *gorm.DB) imUserProhibitedBehavior {
	i.imUserProhibitedBehaviorDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imUserProhibitedBehavior) replaceDB(db *gorm.DB) imUserProhibitedBehavior {
	i.imUserProhibitedBehaviorDo.ReplaceDB(db)
	return i
}

type imUserProhibitedBehaviorDo struct{ gen.DO }

func (i imUserProhibitedBehaviorDo) Debug() *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Debug())
}

func (i imUserProhibitedBehaviorDo) WithContext(ctx context.Context) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imUserProhibitedBehaviorDo) ReadDB() *imUserProhibitedBehaviorDo {
	return i.Clauses(dbresolver.Read)
}

func (i imUserProhibitedBehaviorDo) WriteDB() *imUserProhibitedBehaviorDo {
	return i.Clauses(dbresolver.Write)
}

func (i imUserProhibitedBehaviorDo) Session(config *gorm.Session) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Session(config))
}

func (i imUserProhibitedBehaviorDo) Clauses(conds ...clause.Expression) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imUserProhibitedBehaviorDo) Returning(value interface{}, columns ...string) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imUserProhibitedBehaviorDo) Not(conds ...gen.Condition) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imUserProhibitedBehaviorDo) Or(conds ...gen.Condition) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imUserProhibitedBehaviorDo) Select(conds ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imUserProhibitedBehaviorDo) Where(conds ...gen.Condition) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imUserProhibitedBehaviorDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *imUserProhibitedBehaviorDo {
	return i.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (i imUserProhibitedBehaviorDo) Order(conds ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imUserProhibitedBehaviorDo) Distinct(cols ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imUserProhibitedBehaviorDo) Omit(cols ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imUserProhibitedBehaviorDo) Join(table schema.Tabler, on ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imUserProhibitedBehaviorDo) LeftJoin(table schema.Tabler, on ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imUserProhibitedBehaviorDo) RightJoin(table schema.Tabler, on ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imUserProhibitedBehaviorDo) Group(cols ...field.Expr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imUserProhibitedBehaviorDo) Having(conds ...gen.Condition) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imUserProhibitedBehaviorDo) Limit(limit int) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imUserProhibitedBehaviorDo) Offset(offset int) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imUserProhibitedBehaviorDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imUserProhibitedBehaviorDo) Unscoped() *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imUserProhibitedBehaviorDo) Create(values ...*model.ImUserProhibitedBehavior) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imUserProhibitedBehaviorDo) CreateInBatches(values []*model.ImUserProhibitedBehavior, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imUserProhibitedBehaviorDo) Save(values ...*model.ImUserProhibitedBehavior) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imUserProhibitedBehaviorDo) First() (*model.ImUserProhibitedBehavior, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUserProhibitedBehavior), nil
	}
}

func (i imUserProhibitedBehaviorDo) Take() (*model.ImUserProhibitedBehavior, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUserProhibitedBehavior), nil
	}
}

func (i imUserProhibitedBehaviorDo) Last() (*model.ImUserProhibitedBehavior, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUserProhibitedBehavior), nil
	}
}

func (i imUserProhibitedBehaviorDo) Find() ([]*model.ImUserProhibitedBehavior, error) {
	result, err := i.DO.Find()
	return result.([]*model.ImUserProhibitedBehavior), err
}

func (i imUserProhibitedBehaviorDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ImUserProhibitedBehavior, err error) {
	buf := make([]*model.ImUserProhibitedBehavior, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imUserProhibitedBehaviorDo) FindInBatches(result *[]*model.ImUserProhibitedBehavior, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imUserProhibitedBehaviorDo) Attrs(attrs ...field.AssignExpr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imUserProhibitedBehaviorDo) Assign(attrs ...field.AssignExpr) *imUserProhibitedBehaviorDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imUserProhibitedBehaviorDo) Joins(fields ...field.RelationField) *imUserProhibitedBehaviorDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imUserProhibitedBehaviorDo) Preload(fields ...field.RelationField) *imUserProhibitedBehaviorDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imUserProhibitedBehaviorDo) FirstOrInit() (*model.ImUserProhibitedBehavior, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUserProhibitedBehavior), nil
	}
}

func (i imUserProhibitedBehaviorDo) FirstOrCreate() (*model.ImUserProhibitedBehavior, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ImUserProhibitedBehavior), nil
	}
}

func (i imUserProhibitedBehaviorDo) FindByPage(offset int, limit int) (result []*model.ImUserProhibitedBehavior, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imUserProhibitedBehaviorDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imUserProhibitedBehaviorDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imUserProhibitedBehaviorDo) Delete(models ...*model.ImUserProhibitedBehavior) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imUserProhibitedBehaviorDo) withDO(do gen.Dao) *imUserProhibitedBehaviorDo {
	i.DO = *do.(*gen.DO)
	return i
}
