// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImAvatar = "im_avatar"

// ImAvatar mapped from table <im_avatar>
type ImAvatar struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	Name      string         `gorm:"column:name;type:varchar(64);comment:头像文字" json:"name"`
	FaceURL   string         `gorm:"column:face_url;type:varchar(255);comment:头像" json:"face_url"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
}

// TableName ImAvatar's table name
func (*ImAvatar) TableName() string {
	return TableNameImAvatar
}
