// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImBlack = "im_blacks"

// ImBlack mapped from table <im_blacks>
type ImBlack struct {
	OwnerUserID    string    `gorm:"column:owner_user_id;type:varchar(64);primaryKey;comment:用户的UserID" json:"owner_user_id"`
	BlockUserID    string    `gorm:"column:block_user_id;type:varchar(64);primaryKey;comment:被拉黑用户的UserID" json:"block_user_id"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime(3);comment:添加时间" json:"create_time"`
	AddSource      int32     `gorm:"column:add_source;type:int(11);comment:原因" json:"add_source"`
	OperatorUserID string    `gorm:"column:operator_user_id;type:varchar(64);comment:处理者的UserID" json:"operator_user_id"`
	Ex             string    `gorm:"column:ex;type:varchar(1024);comment:拓展字段" json:"ex"`
}

// TableName ImBlack's table name
func (*ImBlack) TableName() string {
	return TableNameImBlack
}
