// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImFeedback = "im_feedback"

// ImFeedback mapped from table <im_feedback>
type ImFeedback struct {
	ID              int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	UserID          string         `gorm:"column:user_id;type:varchar(64);comment:用户userid" json:"user_id"`
	NickeName       string         `gorm:"column:nicke_name;type:varchar(64);comment:称呼" json:"nicke_name"`
	Contact         string         `gorm:"column:contact;type:varchar(128);comment:联系方式" json:"contact"`
	FeedbackContent string         `gorm:"column:feedback_content;type:text;comment:反馈内容" json:"feedback_content"`
	Imgs            string         `gorm:"column:imgs;type:text;comment:图片url多张用,隔开" json:"imgs"`
	Status          string         `gorm:"column:status;type:varchar(50);default:待处理;comment:状态 已处理和待处理" json:"status"`
	HandleContent   string         `gorm:"column:handle_content;type:text;comment:处理结果内容" json:"handle_content"`
	CreatedAt       time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
	HandlePerson    string         `gorm:"column:handle_person;type:varchar(255);comment:操作人" json:"handle_person"`
}

// TableName ImFeedback's table name
func (*ImFeedback) TableName() string {
	return TableNameImFeedback
}
