// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImFunctionalConfig = "im_functional_config"

// ImFunctionalConfig mapped from table <im_functional_config>
type ImFunctionalConfig struct {
	ID                       int32 `gorm:"column:id;type:int(11);primaryKey" json:"id"`
	ProhibitRegister         int32 `gorm:"column:prohibitRegister;type:tinyint(4);default:2;comment:禁止客户端注册，1-开启，2-没开启" json:"prohibitRegister"`
	ProhibitAddFriend        int32 `gorm:"column:prohibitAddFriend;type:tinyint(4);default:2;comment:禁止普通用户添加好友，1-开启，2-没开启" json:"prohibitAddFriend"`
	ProhibitCreateGroup      int32 `gorm:"column:prohibitCreateGroup;type:tinyint(4);default:2;comment:禁止普通用户建群，1-开启，2-没开启" json:"prohibitCreateGroup"`
	ProhibitGroupSendPicture int32 `gorm:"column:prohibitGroupSendPicture;type:tinyint(4);default:2;comment:禁止群内发送照片，1-开启，2-没开启" json:"prohibitGroupSendPicture"`
	ProhibitGroupSendVideo   int32 `gorm:"column:prohibitGroupSendVideo;type:tinyint(4);default:2;comment:禁止群内发送视频，1-开启，2-没开启" json:"prohibitGroupSendVideo"`
	ProhibitGroupSendCard    int32 `gorm:"column:prohibitGroupSendCard;type:tinyint(4);default:2;comment:禁止群内发送名片，1-开启，2-没开启" json:"prohibitGroupSendCard"`
	ProhibitSearch           int32 `gorm:"column:prohibitSearch;type:tinyint(4);default:2;comment:禁止搜索好友，1-开启，2-没开启" json:"prohibitSearch"`
	MultiplePlatform         int32 `gorm:"column:multiplePlatform;type:tinyint(4);default:1;comment:登录设置，1-单平台，2-多平台" json:"multiplePlatform"`
	Android                  int32 `gorm:"column:android;type:tinyint(4);default:2;comment:允许安卓多平台登录，1-开启，2-没开启" json:"android"`
	Iphone                   int32 `gorm:"column:iphone;type:tinyint(4);default:2;comment:允许iphone多平台登录，1-开启，2-没开启" json:"iphone"`
	Windows                  int32 `gorm:"column:windows;type:tinyint(4);default:2;comment:允许window多平台登录，1-开启，2-没开启" json:"windows"`
	Mac                      int32 `gorm:"column:mac;type:tinyint(4);default:2;comment:允许mac多平台登录，1-开启，2-没开启" json:"mac"`
	ProhibitUserAddUser      int32 `gorm:"column:prohibitUserAddUser;type:tinyint(4);default:2;comment:禁止普通用户添加普通用户，1-开启，2-没开启" json:"prohibitUserAddUser"`
	ProhibitUserAddVip       int32 `gorm:"column:prohibitUserAddVip;type:tinyint(4);default:2;comment:禁止普通用户添加特权用户，1-开启，2-没开启" json:"prohibitUserAddVip"`
	ProhibitVipAddVip        int32 `gorm:"column:prohibitVipAddVip;type:tinyint(4);default:2;comment:禁止特权用户添加特权用户，1-开启，2-没开启" json:"prohibitVipAddVip"`
}

// TableName ImFunctionalConfig's table name
func (*ImFunctionalConfig) TableName() string {
	return TableNameImFunctionalConfig
}
