// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImFriend = "im_friends"

// ImFriend mapped from table <im_friends>
type ImFriend struct {
	OwnerUserID    string    `gorm:"column:owner_user_id;type:varchar(64);primaryKey;comment:用户的UserID" json:"owner_user_id"`
	FriendUserID   string    `gorm:"column:friend_user_id;type:varchar(64);primaryKey;comment:好友的UserID" json:"friend_user_id"`
	Remark         string    `gorm:"column:remark;type:varchar(255);comment:好友备注" json:"remark"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime(3);comment:添加时间" json:"create_time"`
	AddSource      int32     `gorm:"column:add_source;type:int(11);comment:添加来源，1-ID,2-扫码,3-名片，4-群聊，5-其他" json:"add_source"`
	OperatorUserID string    `gorm:"column:operator_user_id;type:varchar(64);comment:处理者的UserID" json:"operator_user_id"`
	Ex             string    `gorm:"column:ex;type:varchar(1024);comment:拓展字段" json:"ex"`
	Status         int32     `gorm:"column:status;type:tinyint(2);default:1;comment:好友状态 0=在黑名单中，1=正常" json:"status"`
	IsDeleted      int32     `gorm:"column:is_deleted;type:tinyint(2);default:1;comment:是否是已删除的好友 1=否，2=是" json:"is_deleted"`
}

// TableName ImFriend's table name
func (*ImFriend) TableName() string {
	return TableNameImFriend
}
