// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImGroupRequest = "im_group_requests"

// ImGroupRequest mapped from table <im_group_requests>
type ImGroupRequest struct {
	UserID        string    `gorm:"column:user_id;type:varchar(64);primaryKey;comment:进群申请者 userID" json:"user_id"`
	GroupID       string    `gorm:"column:group_id;type:varchar(64);primaryKey;comment:群组ID" json:"group_id"`
	HandleResult  int32     `gorm:"column:handle_result;type:int(11);comment:处理结果" json:"handle_result"`
	ReqMsg        string    `gorm:"column:req_msg;type:varchar(1024);comment:申请信息" json:"req_msg"`
	HandleMsg     string    `gorm:"column:handle_msg;type:varchar(1024);comment:处理信息" json:"handle_msg"`
	ReqTime       time.Time `gorm:"column:req_time;type:datetime(3);comment:申请时间" json:"req_time"`
	HandleUserID  string    `gorm:"column:handle_user_id;type:varchar(64);comment:处理者的用户ID" json:"handle_user_id"`
	HandleTime    time.Time `gorm:"column:handle_time;type:datetime(3);comment:处理时间" json:"handle_time"`
	JoinSource    int32     `gorm:"column:join_source;type:int(11);comment:来源" json:"join_source"`
	InviterUserID string    `gorm:"column:inviter_user_id;type:varchar(64);comment:邀请者的用户ID" json:"inviter_user_id"`
	Ex            string    `gorm:"column:ex;type:varchar(1024)" json:"ex"`
}

// TableName ImGroupRequest's table name
func (*ImGroupRequest) TableName() string {
	return TableNameImGroupRequest
}
