// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImIPBlacklist = "im_ip_blacklist"

// ImIPBlacklist mapped from table <im_ip_blacklist>
type ImIPBlacklist struct {
	ID        int64     `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:ID" json:"id"`
	IP        string    `gorm:"column:ip;type:varchar(120);comment:IP" json:"ip"`
	Status    int32     `gorm:"column:status;type:tinyint(4);comment:状态 1=禁止，2=解禁" json:"status"`
	UnbanTime time.Time `gorm:"column:unban_time;type:datetime(3);comment:解禁时间" json:"unban_time"`
	BanTime   time.Time `gorm:"column:ban_time;type:datetime(3);comment:封禁时间" json:"ban_time"`
	EndTime   time.Time `gorm:"column:end_time;type:datetime(3);comment:禁止截止时间" json:"end_time"`
	Remark    string    `gorm:"column:remark;type:varchar(1024);comment:封禁的原因" json:"remark"`
	CreateBy  string    `gorm:"column:create_by;type:varchar(128);not null;comment:创建人" json:"create_by"`
	UpdateBy  string    `gorm:"column:update_by;type:varchar(128);not null;comment:更新人" json:"update_by"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
}

// TableName ImIPBlacklist's table name
func (*ImIPBlacklist) TableName() string {
	return TableNameImIPBlacklist
}
