// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImKefuConversation = "im_kefu_conversations"

// ImKefuConversation mapped from table <im_kefu_conversations>
type ImKefuConversation struct {
	ID          int64     `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	GroupID     string    `gorm:"column:group_id;type:varchar(256);not null;comment:群ID" json:"group_id"`
	UserID      string    `gorm:"column:user_id;type:varchar(64);not null;comment:用户ID" json:"user_id"`
	KefuID      string    `gorm:"column:kefu_id;type:varchar(64);not null;comment:客服ID" json:"kefu_id"`
	DeviceID    string    `gorm:"column:device_id;type:varchar(512);not null;comment:设备的id" json:"device_id"`
	Platform    string    `gorm:"column:platform;type:varchar(255);not null;comment:会话来源(平台)" json:"platform"`
	ServiceType int32     `gorm:"column:service_type;type:tinyint(2);default:1;comment:服务类型 1=多端登录，2=咨询" json:"service_type"`
	Summary     string    `gorm:"column:summary;type:varchar(500);comment:会话总结" json:"summary"`
	StartSeq    string    `gorm:"column:start_seq;type:varchar(60);comment:会话开始信息seq" json:"start_seq"`
	EndSeq      string    `gorm:"column:end_seq;type:varchar(60);comment:会话结束信息seq" json:"end_seq"`
	MsgNum      string    `gorm:"column:msg_num;type:varchar(60);comment:会话信息数量" json:"msg_num"`
	Status      int32     `gorm:"column:status;type:tinyint(2);default:1;comment:处理状态 1=进行中，2=已处理" json:"status"`
	HandleTime  time.Time `gorm:"column:handle_time;type:datetime;comment:处理时间" json:"handle_time"`
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
}

// TableName ImKefuConversation's table name
func (*ImKefuConversation) TableName() string {
	return TableNameImKefuConversation
}
