// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImLoginDevice = "im_login_device"

// ImLoginDevice mapped from table <im_login_device>
type ImLoginDevice struct {
	ID                int32     `gorm:"column:id;type:int(10);primaryKey;autoIncrement:true;comment:设备id" json:"id"`
	UserID            string    `gorm:"column:user_id;type:varchar(255);not null;comment:用户id" json:"user_id"`
	Platform          string    `gorm:"column:platform;type:varchar(255);not null;comment:设备平台" json:"platform"`
	DeviceModel       string    `gorm:"column:device_model;type:varchar(255);comment:设备型号" json:"device_model"`
	Version           string    `gorm:"column:version;type:varchar(255);comment:登录版本" json:"version"`
	IP                string    `gorm:"column:ip;type:varchar(255);comment:ip地址" json:"ip"`
	Status            int32     `gorm:"column:status;type:int(255);comment:在线状态 1 - 正常， 2 - 离线" json:"status"`
	LoginTime         time.Time `gorm:"column:login_time;type:datetime;comment:登录时间" json:"login_time"`
	UpdateTime        time.Time `gorm:"column:update_time;type:datetime;comment:更新时间" json:"update_time"`
	BindDeviceID      string    `gorm:"column:bind_device_id;type:varchar(512);comment:绑定设备的id" json:"bind_device_id"`
	ForceLogoutStatus int32     `gorm:"column:force_logout_status;type:int(1);default:2;comment:是否被强制登出过, 1 - 是强制下线, 2 - 没强制下线" json:"force_logout_status"`
}

// TableName ImLoginDevice's table name
func (*ImLoginDevice) TableName() string {
	return TableNameImLoginDevice
}
