// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImLoginLog = "im_login_log"

// ImLoginLog mapped from table <im_login_log>
type ImLoginLog struct {
	ID         int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UserID     string    `gorm:"column:user_id;type:varchar(255);not null" json:"user_id"`
	Platform   int32     `gorm:"column:platform;type:int(10);not null;comment:平台，IOS:1、安卓:2、window:3、OSX:4、Web:5、小程序:6、Linux:7" json:"platform"`
	LoginIP    string    `gorm:"column:login_ip;type:varchar(255);not null" json:"login_ip"`
	Version    string    `gorm:"column:version;type:varchar(255)" json:"version"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName ImLoginLog's table name
func (*ImLoginLog) TableName() string {
	return TableNameImLoginLog
}
