// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImPrivilegeUserLog = "im_privilege_user_logs"

// ImPrivilegeUserLog mapped from table <im_privilege_user_logs>
type ImPrivilegeUserLog struct {
	FromUserid string    `gorm:"column:from_userid;type:varchar(128);comment:来源id" json:"from_userid"`
	AddType    string    `gorm:"column:add_type;type:varchar(20);comment:类型添加群或者添加好友" json:"add_type"`
	Reson      string    `gorm:"column:reson;type:text;comment:原因" json:"reson"`
	TargetObj  string    `gorm:"column:target_obj;type:varchar(128);comment:目标对象好友或者groupid" json:"target_obj"`
	Times      time.Time `gorm:"column:times;type:datetime" json:"times"`
}

// TableName ImPrivilegeUserLog's table name
func (*ImPrivilegeUserLog) TableName() string {
	return TableNameImPrivilegeUserLog
}
