// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImPrivilegeUserBindLoginDevice = "im_privilege_user_bind_login_device"

// ImPrivilegeUserBindLoginDevice mapped from table <im_privilege_user_bind_login_device>
type ImPrivilegeUserBindLoginDevice struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	UserID    string         `gorm:"column:user_id;type:varchar(64);comment:用户id" json:"user_id"`
	Device    string         `gorm:"column:device;type:varchar(512);comment:绑定的登录设备号" json:"device"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
}

// TableName ImPrivilegeUserBindLoginDevice's table name
func (*ImPrivilegeUserBindLoginDevice) TableName() string {
	return TableNameImPrivilegeUserBindLoginDevice
}
