// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImRobot = "im_robots"

// ImRobot mapped from table <im_robots>
type ImRobot struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	UserID    string         `gorm:"column:user_id;type:varchar(64);comment:用户ID 对应着腾讯的id" json:"user_id"`
	Nickname  string         `gorm:"column:nickname;type:varchar(64);comment:昵称" json:"nickname"`
	FaceURL   string         `gorm:"column:face_url;type:varchar(255);comment:头像" json:"face_url"`
	Gender    int32          `gorm:"column:gender;type:tinyint(2);comment:性别 0=女性，1=男性" json:"gender"`
	Motto     string         `gorm:"column:motto;type:varchar(1024);comment:签名" json:"motto"`
	Status    int32          `gorm:"column:status;type:tinyint(2);comment:状态 0=禁用，1=正常" json:"status"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
}

// TableName ImRobot's table name
func (*ImRobot) TableName() string {
	return TableNameImRobot
}
