// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImSystemMessage = "im_system_message"

// ImSystemMessage mapped from table <im_system_message>
type ImSystemMessage struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	Recipient string         `gorm:"column:recipient;type:varchar(64);not null;comment:接受者,全部或者user_id" json:"recipient"`
	MsgType   string         `gorm:"column:msg_type;type:varchar(64);comment:消息类型" json:"msg_type"`
	Content   string         `gorm:"column:content;type:text;comment:消息内容" json:"content"`
	Remark    string         `gorm:"column:remark;type:varchar(64);comment:备注" json:"remark"`
	Status    string         `gorm:"column:status;type:varchar(11);not null;comment:成功或者失败" json:"status"`
	SendTime  int64          `gorm:"column:send_time;type:bigint(20);comment:发送时间" json:"send_time"`
	CreatedBy string         `gorm:"column:created_by;type:varchar(64);comment:创建人" json:"created_by"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
}

// TableName ImSystemMessage's table name
func (*ImSystemMessage) TableName() string {
	return TableNameImSystemMessage
}
