// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImSecurityQuestion = "im_security_questions"

// ImSecurityQuestion mapped from table <im_security_questions>
type ImSecurityQuestion struct {
	ID         int32  `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`
	Question   string `gorm:"column:question;type:varchar(255)" json:"question"`
	QuestionEn string `gorm:"column:question_en;type:varchar(255)" json:"question_en"`
}

// TableName ImSecurityQuestion's table name
func (*ImSecurityQuestion) TableName() string {
	return TableNameImSecurityQuestion
}
