// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImSensitiveWord = "im_sensitive_words"

// ImSensitiveWord mapped from table <im_sensitive_words>
type ImSensitiveWord struct {
	ID             int32     `gorm:"column:id;type:int(10);primaryKey;autoIncrement:true;comment:ID" json:"id"`
	Word           string    `gorm:"column:word;type:varchar(64);not null;comment:敏感词" json:"word"`
	Status         int32     `gorm:"column:status;type:tinyint(4);not null;comment:状态 0=禁用，1=启用" json:"status"`
	LibID          string    `gorm:"column:lib_id;type:varchar(64);not null;comment:词库 ID" json:"lib_id"`
	Label          string    `gorm:"column:label;type:varchar(64);not null;comment:敏感词分类：Normal/Illegal/Abuse/Polity/Ad/Porn/Sexy/Terror/Composite" json:"label"`
	OperatorUserID string    `gorm:"column:operator_user_id;type:varchar(64);comment:操作者的UserID" json:"operator_user_id"`
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime(3);comment:添加时间" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:datetime(3);comment:更新时间" json:"updated_at"`
}

// TableName ImSensitiveWord's table name
func (*ImSensitiveWord) TableName() string {
	return TableNameImSensitiveWord
}
