// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImUserSecurityQuestion = "im_user_security_questions"

// ImUserSecurityQuestion mapped from table <im_user_security_questions>
type ImUserSecurityQuestion struct {
	UserID     string    `gorm:"column:user_id;type:varchar(64)" json:"user_id"`
	QuestionID int32     `gorm:"column:question_id;type:int(10) unsigned" json:"question_id"`
	Answer     string    `gorm:"column:answer;type:varchar(255)" json:"answer"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime(3)" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime(3)" json:"update_time"`
}

// TableName ImUserSecurityQuestion's table name
func (*ImUserSecurityQuestion) TableName() string {
	return TableNameImUserSecurityQuestion
}
