// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImUserProhibitedBehavior = "im_user_prohibited_behavior"

// ImUserProhibitedBehavior mapped from table <im_user_prohibited_behavior>
type ImUserProhibitedBehavior struct {
	UserID     string    `gorm:"column:user_id;type:varchar(64);not null;comment:用户ID" json:"user_id"`
	Account    string    `gorm:"column:account;type:varchar(64);comment:帐户ID" json:"account"`
	Nickname   string    `gorm:"column:nickname;type:varchar(64);comment:昵称" json:"nickname"`
	ActionType int32     `gorm:"column:action_type;type:tinyint(4);comment:行为类型 1=私聊禁言，2=群聊禁言，3=群聊禁言，3=禁止创建群聊，4=禁止登录" json:"action_type"`
	EndTime    time.Time `gorm:"column:end_time;type:datetime(3);comment:禁止截止时间" json:"end_time"`
	CreateBy   string    `gorm:"column:create_by;type:varchar(128);not null;comment:创建人" json:"create_by"`
	UpdateBy   string    `gorm:"column:update_by;type:varchar(128);not null;comment:更新人" json:"update_by"`
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	Remark     string    `gorm:"column:remark;type:varchar(300);not null;comment:封禁备注" json:"remark"`
}

// TableName ImUserProhibitedBehavior's table name
func (*ImUserProhibitedBehavior) TableName() string {
	return TableNameImUserProhibitedBehavior
}
