// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImUserCode = "im_user_code"

// ImUserCode mapped from table <im_user_code>
type ImUserCode struct {
	ID        int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:id" json:"id"`
	Account   string    `gorm:"column:account;type:varchar(255);comment:账号名" json:"account"`
	UserID    string    `gorm:"column:user_id;type:varchar(255);comment:用户id" json:"user_id"`
	Code      string    `gorm:"column:code;type:varchar(255);comment:验证码" json:"code"`
	IsUsed    int32     `gorm:"column:is_used;type:int(1);default:1;comment:是否已经使用，1-未使用，2-已使用" json:"is_used"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	ExpiredAt time.Time `gorm:"column:expired_at;type:datetime;comment:过期时间" json:"expired_at"`
}

// TableName ImUserCode's table name
func (*ImUserCode) TableName() string {
	return TableNameImUserCode
}
