// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImUsersDeviceConf = "im_users_device_conf"

// ImUsersDeviceConf mapped from table <im_users_device_conf>
type ImUsersDeviceConf struct {
	UserID           string    `gorm:"column:user_id;type:varchar(255);primaryKey;comment:用户id" json:"user_id"`
	MultiplePlatform int32     `gorm:"column:multiplePlatform;type:tinyint(4);comment:多平台，1-单平台，2-多平台" json:"multiplePlatform"`
	Android          int32     `gorm:"column:android;type:tinyint(4);default:2;comment:android平台,1-开通，2-没开通" json:"android"`
	Iphone           int32     `gorm:"column:iphone;type:tinyint(4);default:2;comment:iphone平台,1-开通，2-没开通" json:"iphone"`
	Windows          int32     `gorm:"column:windows;type:tinyint(4);default:2;comment:windows平台,1-开通，2-没开通" json:"windows"`
	Mac              int32     `gorm:"column:mac;type:tinyint(4);default:2;comment:mac平台,1-开通，2-没开通" json:"mac"`
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
}

// TableName ImUsersDeviceConf's table name
func (*ImUsersDeviceConf) TableName() string {
	return TableNameImUsersDeviceConf
}
